Allow to define wether the entity cache should be reset prior to deletion
Metadrop/behat-contexts pull request #102
Opened 2021-05-14 10:59 UTC by idiazroncero

On some scenarios, the `entityDelete()` methods won't receive an updated version of the entity to delete (the entity could have been changed because, as part of the test, some values were implicit or explicitly changed).

This can lead to errors if there are some dependencies. In the case of Subgroup, the Group entity was cached and the values that reflect the hierarchy were missing when the deletion was triggered. This led to exceptions.

There is a new parameter ($reset_caches) that can be passed to entity deletion methods. This parameter will ensure that an up-to-date entity is deleted.

2021-05-14 11:03 UTC, jorgetutor commented
@idiazroncero why using a parameter if every time it is being called a TRUE is sent?
Maybe if is easier to always reset the cache. In the future, if we see a scenario where it is not needed then we can add the param.
What do you think?

2021-05-14 11:09 UTC, idiazroncero commented
@rsanzante and I talked about it and decided to go this way in order to avoid breaking things in other projects (i.e somebody could be making a call to these methods on some custom code) and thus allow developers to opt-in into this new feature instead of enforcing it by default.

2021-05-14 11:12 UTC, jorgetutor commented
@idiazroncero I don't understand, every time the method is called the param is TRUE, so if someone updates the library it will work always that way.

2021-05-14 11:13 UTC, idiazroncero commented
I was referring to `entityDelete` and `entityDeleteMultiple`. Yes, they are usually not called directly, but they may be (we don't have a way to know).

2021-05-14 11:26 UTC, rsanzante requested changes

2021-05-14 11:26 UTC, rsanzante commented on src/Behat/Cores/Drupal7.php
>      return entity_delete($entity_type, $entity_id);
I would add a @TODO to say currently we are not resetting cache for Drupal.

2021-05-14 11:26 UTC, rsanzante commented on src/Behat/Cores/Drupal7.php
>      return entity_delete_multiple($entity_type, $entities_ids);
Same, here: add a @TODO to say currently we are not resetting cache for Drupal.

2021-05-14 19:08 UTC, mistermoper commented on src/Behat/Cores/CoreInterface.php
> +   *   Wether the entity caches should be reset before loading them
Could you add a comment explaining why reset cache is default to FALSE, with an specific use case that justifies it.

2021-05-14 19:10 UTC, mistermoper commented
> I was referring to `entityDelete` and `entityDeleteMultiple`. Yes, they are usually not called directly, but they may be (we don't have a way to know).

I've added this comment:

https://github.com/Metadrop/behat-contexts/pull/102/files#r632741051

To solve this discussion, may you add a comment in the code that explains this decision, with a use case that justifies it?

2021-05-18 11:40 UTC, mistermoper commented
Is it fine enough, the improvements commented can be done later if neccesary.

2021-05-18 11:40 UTC, merged