Upload media independent of language
Metadrop/behat-contexts pull request #150
Opened 2023-03-14 11:44 UTC by albeorte96

Currently, the media upload step contains the string "Select " which makes the step incompatible if you are not using English on the website.

I have added and checked a correction to be able to upload media independently of the language of the site where Behat tests are being launched.

2023-03-14 12:10 UTC, mistermoper commented on src/Behat/Context/MediaContext.php
> +      $xpath = "//*[@id='drupal-modal']//label[contains(text(),'". $media_title ."')]/following-sibling::input";
This works in most cases but with this strategy, we are not sure if we are clicking the correct button. There may be more buttons in special cases.

To solve this, can you check if the <input> element that is being selected at the end of the Xpath has a specific attribute that allow us to be sure that is the correct element? If so, please add that attribute to the XPath query

2023-03-16 14:45 UTC, mistermoper requested changes
https://github.com/Metadrop/behat-contexts/pull/150/files#r1135445223

2023-11-07 11:15 UTC, omarlopesino commented on src/Behat/Context/MediaContext.php
> +      $xpath = "//*[@id='drupal-modal']//label[contains(text(),'". $media_title ."')]/following-sibling::input";
Xpath improved. Tested on a project that needed this fix.

2023-11-07 11:15 UTC, omarlopesino approved these changes

2023-11-07 11:15 UTC, merged